# Generated by Django 5.2.7 on 2025-10-04 18:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("upload_path", models.TextField()),
                ("normalized_path", models.TextField(blank=True, null=True)),
                ("upload_rel", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "normalized_rel",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("src_size", models.BigIntegerField(blank=True, null=True)),
                ("wav_size", models.BigIntegerField(blank=True, null=True)),
                ("duration_sec", models.FloatField(blank=True, null=True)),
                ("full_text", models.TextField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
