# Generated by Django 5.2.7 on 2025-10-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_uploadjob_session_key_uploadjob_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadjob",
            name="original_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="stored_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
