# Generated by Django 5.2.7 on 2025-10-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_uploadjob_original_name_uploadjob_stored_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadjob",
            name="original_name",
        ),
        migrations.RemoveField(
            model_name="uploadjob",
            name="stored_name",
        ),
    ]
