# Generated by Django 5.2.7 on 2025-10-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_remove_uploadjob_original_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadjob",
            name="original_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="stored_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
