# Generated by Django 5.2.7 on 2025-10-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_uploadjob_original_name_uploadjob_stored_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadjob",
            options={"ordering": ["-created_at"]},
        ),
    ]
